### ISSUE TITLE
右边栏错位

### ISSUE THREAD

**Issue by Gaojianli** [RainEggplant/rain-classroom-helper#8]
![image](https://user-images.githubusercontent.com/19235246/74903533-2795d080-53e4-11ea-8c1e-4b34d42bbf94.png)

**Comment by RainEggplant** [comment]
检查发现不启用插件也会出现这种情况。原因是雨课堂的开发人员理所当然地认为列表中每五个元素会换一行，从而用 `:nth-child(5)` 选择器每隔 5 个元素改变了样式。
